### ISSUE TITLE
Creating torrent

### ISSUE THREAD

**Issue by webzi** [overfl0/Bulletproof-Arma-Launcher#188] opened 2017-01-30 22:38 UTC
Hi Overfl0,

I really love this launcher, great work!

Is there any chance you can give a quick step by step to build a torrent?

I tried my self, but it seems like the launcher is looking for 2 different torrent files? 

The error I'm getting is the same as the one you just reopenede.

"An error occurred in a subprocess:
Build: 0a2f549e2f8fa10371d07dca44c0d3a280cf0f36
Traceback (most recent call last):
  File "process.py", line 332, in _protected_call
  File "sync\manager_functions.py", line 401, in _sync_all
  File "sync\torrentsyncer.py", line 462, in sync
RuntimeError: torrent already exists in session"

**Comment by overfl0** [comment] 2017-01-31 01:26
Hi, I'm answering from my phone, in the middle of the night so excuse my brevity.

I'll fix the bug tomorrow, now that I have a reproduction.

You've not made it clear so I have to ask: are you trying to make a Fork of the launcher for your community?
If not, there is no point in creating a torrent yourself.
If yes, then consider waiting until Sunday when I'll push a big change in how multiple launchers are used with the same codebase (see newui branch for a sneak peek).

Creating and updating torrents is very rough now and done semi-automatically now because I never had the time to polish that part of the launcher. I'm also considering changing much stuff with how metadata.json will be used so if you want to use the launcher code better tell me so I take more care in modifying it.

**Comment by webzi** [comment] 2017-01-31 01:31
Hi, thanks for your answer.

Yeah, I was thinking about using this launcher for my community, since it's seems pretty nice and user friendly ;-) 

I'll stick around and wait for an update on the repo.

Thanks for you time

**Comment by overfl0** [comment] 2017-02-06 23:35
Hey!
The update was ready (and has actually been merged yesterday) but it took me a whole day today (6 hours) to write everything down and explain how the launcher was working.

See this link for everything you should need to know: https://github.com/overfl0/Bulletproof-Arma-Launcher/wiki/Launcher-management

Requirements have also changed so I suggest you to redo everything from scratch, that is to do the following in the build environment directory:
```
vagrant destroy
git pull
vagrant up
```

Actually, if you would like to talk live, you can find me on TacBF's discord or on Frontline discord: http://discord.frontline.frl channel: #launcher

This way, I could close this issue :).

**Closed** 2017-02-07 11:15 UTC
